### ISSUE TITLE
Add Media Queries for 'Versus' 

### ISSUE THREAD

**Issue by ianarsenault** [ianarsenault/Pulse-Roshambo#22]
Mainly in part as I don't know how this looks on 13" laptops. 
Add some sort of media query to check max and min width of a screen to update the Versus between player cards. 

Currently between `768px` and `1216px` the "versus" becomes a mess.

![image](https://i.imgur.com/c4iCYRb.png)

Maybe add our own font size class instead of using bulmas `title` and `is-1`

And just use something like

```css

@media only screen
and (min-width: 768px)
and (max-width: 993px) {
    versus-font {
         font-size: 2.25rem;
    }
}

/** Do the same for larger screen size up to 1216px **/
```

If this is the way to go I could probably tackle this.
